import AddSelectTag from '@/components/AddSelectTag';
import Select, { SelectOption } from '@/components/Select';
import Head from 'next/head';
import { useState } from 'react';
import { options } from '../utils/Options';

export default function Home() {
    const [value, setValue] = useState<SelectOption | undefined>(options[0]);
    const [mutltipleValue, setMultipleValue] = useState<SelectOption[]>([
        options[0],
    ]);

    return (
        <>
            <Head>
                <title>Select Component</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AddSelectTag />
            <br />
            <Select
                multiple={true}
                options={options}
                value={mutltipleValue}
                onChange={(v) => setMultipleValue(v)}
            />
            <br />
            <br />
            <Select
                multiple={false}
                options={options}
                value={value}
                onChange={(v) => setValue(v)}
            />
        </>
    );
}
